### ISSUE TITLE
Window not showing with sleep()

### ISSUE THREAD

**Issue by pmerku** [harm-smits/42docs#14]
In "Getting started", second snippet: the window doesn't pop up while using sleep(). Works with mlx_loop(), but some workarounds have to be done to close the window without stopping it in the terminal manually.

```c
#include <mlx.h>
#include <stdlib.h>

int 	exit2()
{
	exit(0);
}

int     main(void)
{
	void    *mlx;
	void    *mlx_win;

	mlx = mlx_init();
	mlx_win = mlx_new_window(mlx, 1920, 1080, "Hello world!");
	mlx_hook(mlx_win, 17, 0, exit2, mlx);
	mlx_loop(mlx);
}
```

**Comment by harm-smits** [comment]
Seems because of that the entire getting started part is broken. Will update the snippets accordingly.
