### ISSUE TITLE
MiniLibX documentation - Getting a screen on WSL

### ISSUE THREAD

**Issue by pleymate** [harm-smits/42docs#34]
Hello,

Thank you very much for your documentation regarding MLX. It has been very useful to me, and I'm sure to plenty others.
There's an error in section Getting Started > Getting a screen on WSL(2).
Upon opening XLaunch, user should choose "Start no client" option, rather than "Start a program" as stated in the documentation.

Thank you again!

**Comment by harm-smits** [comment]
@VincentBotte This issue has been resolved. Thanks for the heads up!
